### ISSUE TITLE
Not using user defined read format

### ISSUE THREAD

**Issue by cclinard84-zz** [OpenMTR/openmtr-api#34]
Alot of reads come back with false negatives due to rest service overriding user defined read formats.

https://github.com/OpenMTR/openmtr-api/blob/cf78118fc8516a6c7874681bd2489575e366df2f/src/main/java/com/openmtr/api/services/OpenMeterApi.java#L185

**Comment by jameswillhoite** [comment]
This is will be fixed with next merge.

**Comment by cclinard84-zz** [comment]
Closed: Moving in a different direction.
