### ISSUE TITLE
Image error handling redundancy

### ISSUE THREAD

**Issue by cclinard84-zz** [OpenMTR/openmtr-api#71]
https://github.com/OpenMTR/openmtr-api/blob/e695f6748e62d5d6b8a265d52fe6855ac1f09f9c/src/main/java/com/openmtr/api/services/PostRequest.java#L75

I think we may just want to return true in this aforementioned method . There are already image checks [here](https://github.com/OpenMTR/openmtr-api/blob/e695f6748e62d5d6b8a265d52fe6855ac1f09f9c/src/main/java/com/openmtr/api/services/PostRequest.java#L38), in the api, and on the client. 

With this change we can also remove [line 61](https://github.com/OpenMTR/openmtr-api/blob/02d8bd8ce3d617fb2853eebbe624a8127c1601f2/src/main/java/com/openmtr/api/services/OpenMeterApi.java#L61) through 64 of OpenMtrApi.java.

**Comment by jameswillhoite** [comment]
This function is what actually saves the image to file. I leave it for last so it doesn't save the image if the user gives incorrect email address, number of dials etc.
