### ISSUE TITLE
Add eclipse specific attributes to the .gitignore

### ISSUE THREAD

**Issue by cclinard84-zz** [OpenMTR/openmtr-api#8]
Currently PR's using eclipse are getting a lot of unnecessary fluff. Harden the .gitignore with eclipse based attributes.

**Comment by MThomas191** [comment]
This issue was fixed soon after being opened by James. When the repo was After, the file caused an issue with ignoring a .jar file, so it was changed.

**Comment by MThomas191** [comment]
Reopening to keep track of the issue, Will close when fate of gitignore .jar files is determined.
